"""001_initial_schema

Revision ID: ea4f99e285b3
Revises: 
Create Date: 2026-08-19 00:23:10.472522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea4f99e285b3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('administrator', 'survey_technician')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buildings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_buildings_project_id', 'buildings', ['project_id'], unique=False)
    op.create_table('project_members',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    op.create_index('idx_project_members_project_id', 'project_members', ['project_id'], unique=False)
    op.create_index('idx_project_members_user_id', 'project_members', ['user_id'], unique=False)
    op.create_table('floors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('building_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_floors_building_id', 'floors', ['building_id'], unique=False)
    op.create_table('survey_areas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('floor_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_survey_areas_floor_id', 'survey_areas', ['floor_id'], unique=False)
    op.create_table('floor_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('survey_area_id', sa.UUID(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=True),
    sa.Column('width_px', sa.Integer(), nullable=True),
    sa.Column('height_px', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('height_px IS NULL OR height_px > 0', name='ck_floor_plans_height_px'),
    sa.CheckConstraint('width_px IS NULL OR width_px > 0', name='ck_floor_plans_width_px'),
    sa.ForeignKeyConstraint(['survey_area_id'], ['survey_areas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_floor_plans_survey_area_id', 'floor_plans', ['survey_area_id'], unique=False)
    op.create_table('simple_maps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('survey_area_id', sa.UUID(), nullable=False),
    sa.Column('artifact_reference', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['survey_area_id'], ['survey_areas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_simple_maps_survey_area_id', 'simple_maps', ['survey_area_id'], unique=False)
    op.create_table('surveys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('survey_area_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('floor_plan_id', sa.UUID(), nullable=True),
    sa.Column('simple_map_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(mode = 'floor_plan' AND floor_plan_id IS NOT NULL AND simple_map_id IS NULL) OR (mode = 'simple_map' AND simple_map_id IS NOT NULL AND floor_plan_id IS NULL) OR (mode = 'location_survey' AND floor_plan_id IS NULL AND simple_map_id IS NULL)", name='ck_surveys_mode_reference_consistency'),
    sa.CheckConstraint("(status = 'completed' AND completed_at IS NOT NULL) OR (status = 'in_progress' AND completed_at IS NULL)", name='ck_surveys_completion_consistency'),
    sa.CheckConstraint("mode IN ('floor_plan', 'simple_map', 'location_survey')", name='ck_surveys_mode'),
    sa.CheckConstraint("status IN ('in_progress', 'completed')", name='ck_surveys_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['floor_plan_id'], ['floor_plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['simple_map_id'], ['simple_maps.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['survey_area_id'], ['survey_areas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_surveys_status', 'surveys', ['status'], unique=False)
    op.create_index('idx_surveys_survey_area_id', 'surveys', ['survey_area_id'], unique=False)
    op.create_table('spatial_positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('survey_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_spatial_positions_survey_id', 'spatial_positions', ['survey_id'], unique=False)
    op.create_table('floor_plan_positions',
    sa.Column('spatial_position_id', sa.UUID(), nullable=False),
    sa.Column('x', sa.Double(), nullable=False),
    sa.Column('y', sa.Double(), nullable=False),
    sa.CheckConstraint('x >= 0 AND x <= 1', name='ck_floor_plan_positions_x'),
    sa.CheckConstraint('y >= 0 AND y <= 1', name='ck_floor_plan_positions_y'),
    sa.ForeignKeyConstraint(['spatial_position_id'], ['spatial_positions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('spatial_position_id')
    )
    op.create_table('location_fixes',
    sa.Column('spatial_position_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Double(), nullable=False),
    sa.Column('longitude', sa.Double(), nullable=False),
    sa.Column('accuracy_meters', sa.Double(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('accuracy_meters > 0', name='ck_location_fixes_accuracy_meters'),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90', name='ck_location_fixes_latitude'),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name='ck_location_fixes_longitude'),
    sa.ForeignKeyConstraint(['spatial_position_id'], ['spatial_positions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('spatial_position_id')
    )
    op.create_table('scan_cycles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('survey_id', sa.UUID(), nullable=False),
    sa.Column('spatial_position_id', sa.UUID(), nullable=True),
    sa.Column('captured_at_wallclock', sa.DateTime(timezone=True), nullable=False),
    sa.Column('android_scan_timestamp_raw', sa.Numeric(), nullable=True),
    sa.Column('fresh_results', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['spatial_position_id'], ['spatial_positions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scan_cycles_captured_at_wallclock', 'scan_cycles', ['captured_at_wallclock'], unique=False)
    op.create_index('idx_scan_cycles_spatial_position_id', 'scan_cycles', ['spatial_position_id'], unique=False)
    op.create_index('idx_scan_cycles_survey_id', 'scan_cycles', ['survey_id'], unique=False)
    op.create_table('simple_map_positions',
    sa.Column('spatial_position_id', sa.UUID(), nullable=False),
    sa.Column('x', sa.Double(), nullable=False),
    sa.Column('y', sa.Double(), nullable=False),
    sa.CheckConstraint('x >= 0 AND x <= 1', name='ck_simple_map_positions_x'),
    sa.CheckConstraint('y >= 0 AND y <= 1', name='ck_simple_map_positions_y'),
    sa.ForeignKeyConstraint(['spatial_position_id'], ['spatial_positions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('spatial_position_id')
    )
    op.create_table('wifi_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_cycle_id', sa.UUID(), nullable=False),
    sa.Column('ssid', sa.Text(), nullable=True),
    sa.Column('bssid', sa.Text(), nullable=False),
    sa.Column('rssi_dbm', sa.Integer(), nullable=False),
    sa.Column('frequency_mhz', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Integer(), nullable=True),
    sa.Column('channel_source', sa.Text(), nullable=False),
    sa.Column('capabilities', sa.Text(), nullable=True),
    sa.CheckConstraint('frequency_mhz > 0', name='ck_wifi_observations_frequency_mhz'),
    sa.ForeignKeyConstraint(['scan_cycle_id'], ['scan_cycles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wifi_observations_bssid', 'wifi_observations', ['bssid'], unique=False)
    op.create_index('idx_wifi_observations_scan_cycle_id', 'wifi_observations', ['scan_cycle_id'], unique=False)
    op.create_index('idx_wifi_observations_scan_cycle_id_bssid', 'wifi_observations', ['scan_cycle_id', 'bssid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_wifi_observations_scan_cycle_id_bssid', table_name='wifi_observations')
    op.drop_index('idx_wifi_observations_scan_cycle_id', table_name='wifi_observations')
    op.drop_index('idx_wifi_observations_bssid', table_name='wifi_observations')
    op.drop_table('wifi_observations')
    op.drop_table('simple_map_positions')
    op.drop_index('idx_scan_cycles_survey_id', table_name='scan_cycles')
    op.drop_index('idx_scan_cycles_spatial_position_id', table_name='scan_cycles')
    op.drop_index('idx_scan_cycles_captured_at_wallclock', table_name='scan_cycles')
    op.drop_table('scan_cycles')
    op.drop_table('location_fixes')
    op.drop_table('floor_plan_positions')
    op.drop_index('idx_spatial_positions_survey_id', table_name='spatial_positions')
    op.drop_table('spatial_positions')
    op.drop_index('idx_surveys_survey_area_id', table_name='surveys')
    op.drop_index('idx_surveys_status', table_name='surveys')
    op.drop_table('surveys')
    op.drop_index('idx_simple_maps_survey_area_id', table_name='simple_maps')
    op.drop_table('simple_maps')
    op.drop_index('idx_floor_plans_survey_area_id', table_name='floor_plans')
    op.drop_table('floor_plans')
    op.drop_index('idx_survey_areas_floor_id', table_name='survey_areas')
    op.drop_table('survey_areas')
    op.drop_index('idx_floors_building_id', table_name='floors')
    op.drop_table('floors')
    op.drop_index('idx_project_members_user_id', table_name='project_members')
    op.drop_index('idx_project_members_project_id', table_name='project_members')
    op.drop_table('project_members')
    op.drop_index('idx_buildings_project_id', table_name='buildings')
    op.drop_table('buildings')
    op.drop_table('projects')
    op.drop_table('users')
    # ### end Alembic commands ###
